title: Madhava Nadimpalli |CSPO
logo:
Description : Product Manager/Product owner |CAT Digital 
Show_download : false
email: madhavadnadimpalli@gmail.com
theme: jekyll-theme-minimal
Social_links: 
   Linkedin : https://www.linkedin.com/in/madhava-nadimpalli-313b20144/
Social_links: 
    GitHub : https://www.github.com/MadhavaDNadimpalli

