title: Madhava Nadimpalli |CSPO
logo:
Description : Product Manager/Product owner |CAT Digital 
email: madhavadnadimpalli@gmail.com
Show_download : false
Social_links: 
   Linkedin : https://www.linkedin.com/in/madhava-nadimpalli-313b20144/
Social_links: 
    GitHub : https://www.github.com/MadhavaDNadimpalli

theme: jekyll-theme-minimal
