title: Madhava Nadimpalli |CSPO
logo:
Description : Product Manager/Product owner |CAT Digital 
Show_download : false
theme: jekyll-theme-minimal
Description : <h3 align="left">Connect with me:</h3>
<p align="left">
<a href="https://linkedin.com/in/https://www.linkedin.com/in/madhava-nadimpalli-313b20144/" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="https://www.linkedin.com/in/madhava-nadimpalli-313b20144/" height="30" width="40" /></a>
</p>
