title: Madhava Nadimpalli |CSPO
logo:
Description : Product Manager/Product owner |CAT Digital 
Show_download : false
theme: jekyll-theme-minimal
 links:
    - title: Linkedin
      url: https://www.linkedin.com/in/madhava-nadimpalli-313b20144/
      icon: fab fa-twitter-square
    - title: Email
      description: madhavadnadimpalli@gmail.com
      icon: fab fa-Gmail
    - title: GitHub
      url: https://github.com/MadhavaDNadimpalli
      icon: fab fa-github-square
